### ISSUE TITLE
Uploaded binary files differ from originals

### ISSUE THREAD

**Issue by NewPlayer2** [dilab/resumable.php#2]
Installed with composer and used the upload.php code from under "How to use".

Large finished files under the uploads directory DO NOT match the originals. This makes the whole script useless.

**Comment by dilab** [comment]
What kind of binary files did you try to upload?

And was the file size matching?

More information would be helpful.

**Comment by georaldc** [comment]
A few issues I see here:
1. When combining chunked files, the order is messed up due to not being naturally sorted. Running natsort against the $chunkFiles array inside the createFileFromChunks should fix this.
2. Sometimes, the folder holding your temp chunked files gets deleted first before the process of combining files gets completed. You then end up with errors such as being unable to call file_get_contents('/path/to/chunked/file') due to the file getting deleted.
3. Haven't tested this fully yet but it looks like fopen in append mode doesn't work well with certain types of files like large binary files. Cake's File class' append method uses this and well, it just breaks the resulting file. Modifying the createFileFromChunks() method to do something similar to how the other PHP implementation sample (https://github.com/23/resumable.js/blob/master/samples/Backend%20on%20PHP.md) works fixes this issue. Quick example below

```
public function createFileFromChunks($chunkFiles, $destFile)
{ 
    natsort($chunkFiles);
    if (($fp = fopen($destFile, 'w')) !== false) {
        foreach ($chunkFiles as $chunkFile) {
            if (fwrite($fp, file_get_contents($chunkFile))) {
                unlink($chunkFile);
            }
        }
        fclose($fp);
    }
    return true;
}
```

I would imagine combining these 3 should fix the issues encountered by @NewPlayer2 

EDIT:
I may be wrong with _#_2. I think the reason for that error is because on certain uploads, the isFileUploadComplete method returns true multiple times at the end of some chunks. Might be something wrong with your math but I think you can just use the resumableTotalChunks value to determine the exact number of chunks resumable has created. The error in _#_3 might also be related to this.

**Comment by dilab** [comment]
I will try to replicate the issues as soon as I have some free time.

Looks like I will have to test couple of file formats:
1. video
2. binary

**Comment by dilab** [comment]
added condition to delete tmp folder only when file is combined from chunks.

**Comment by dilab** [comment]
Issues should be fixed with 0.1.2.

**Comment by daitam** [comment]
The problem still persists with partly uploaded ZIP files. If you try to reupload after page refresh, then uploaded file is corrupted and file size doesn't match original file.

Solved this by using @georaldc solution:
```php
public function createFileFromChunks($chunkFiles, $destFile)
{ 
    $this->log('Beginning of create files from chunks');

    natsort($chunkFiles);
    
    if (($fp = fopen($destFile, 'w')) !== false) {
        foreach ($chunkFiles as $chunkFile) {
            fwrite($fp, file_get_contents($chunkFile));

            $this->log('Append ', ['chunk file' => $chunkFile]);
        }
        fclose($fp);
    }

    $this->log('End of create files from chunks');
    return true;
}
```

Also dropped out _unlink(...)_, because we have _$tmpFolder->delete();_ which deletes whole folder and everything inside it.
